### ISSUE TITLE
Whats the state of this project?

### ISSUE THREAD

**Issue by virtualize** [absolute-quantum/DoctrineEncryptBundle#71]
@absolute-quantum Thank your for maintaining this project!

Looking at the issues and pull requests, there seems to be not much activity. So we would like the know what the state of this project is. We do want to use it (and contribute if required), but are uncertain about its future and like to avoid any technical dept.

If you don't have the time to maintain it, what do you think about moving this project to an organisation where more people could have a look on issues and pull requests?

@Zombaya brought the idea up in this [PR (comment)](https://github.com/absolute-quantum/DoctrineEncryptBundle/pull/65#issuecomment-1176558008) an we think it might be a good one. 

@absolute-quantum What do you think?

**Comment by gimler** [comment]
any update?

**Comment by absolute-quantum** [comment]
https://github.com/absolute-quantum/DoctrineEncryptBundle/pull/65#issuecomment-1476301156

**Comment by r3hp1c** [comment]
Due to various Doctrine ORM deprecations including:
* getEntity() is deprecated
* getEntityManager() is deprecated
* Using Doctrine subscribers as services is deprecated, declare listeners instead

Discussions in this pull https://github.com/absolute-quantum/DoctrineEncryptBundle/pull/65 request.

These 2 comments specifically:
* https://github.com/absolute-quantum/DoctrineEncryptBundle/pull/65#issuecomment-1476301156
* https://github.com/absolute-quantum/DoctrineEncryptBundle/pull/65#issuecomment-1178882618

I need to ensure that my projects will be able to upgrade to new versions of packages and not fall behind, so I created the 
DoctrineEncryptBundle organisation forked the pull request's repository from integr8rs:master-fixes and created the following package
https://packagist.org/packages/doctrineencryptbundle/doctrine-encrypt-bundle

I know about some issues in the version I released (5.3.0) Example: issue (https://github.com/DoctrineEncryptBundle/DoctrineEncryptBundle/issues/1) 
that have already been closed.  It will be in a release in the next couple days as I do plan on looking fixing a few issues that I know about.

I do need to still add another Owner and probably more members to the organisation. Volunteers would be appreciated.

**Comment by virtualize** [comment]
Closing thanks to @r3hp1c how created this community fork:
https://github.com/DoctrineEncryptBundle/DoctrineEncryptBundle
